### ISSUE TITLE
gmail/g suite blocking signup verification?

### ISSUE THREAD

**Issue by itsrobbyg** [mattheworres/hootdraft#52]
I'm using G Suite to manage my business email. When registering a new manager account the confirmation email never arrived. When using my yahoo email the confirmation did arrive. I've had problems like this with an eblast program I developed for clients and IIRC it was due to gmail DKIM issues.

**Comment by mattheworres** [comment]
Assuming you mean registering on phpdraft.com?

**Comment by mattheworres** [comment]
I'll take a peek and see if I can't improve the setup I have right now. I recently revamped the emails the system sends out, so I will compare and see when the new version goes live shortly if it improves the score on mail-tester.com

**Comment by itsrobbyg** [comment]
Yes, the "auto verification" email.

    On Saturday, January 26, 2019, 11:34:55 AM CST, Matthew Orres <notifications@github.com> wrote:  
 
 
Assuming you mean registering on phpdraft.com?

**Comment by mattheworres** [comment]
For what it's worth, my corporate email is also managed by G Suite, and I was able to receive an email from the site without issue, so perhaps the improved formatting (I also see that I've since bumped it up to a 10/10 rating by mail-tester.com) is pleasing to G-Suite. Please report back and let me know, thanks!

**Comment by itsrobbyg** [comment]
Hey there,
Earlier today I registered using my regular gmail account (no G Suite involved) and did not receive a confirmation email (it's been a couple of hours). I am willing to test again using my G Suite account but I believe you would have to delete that account (itsrobbyg@pixelbobs.com) before doing so.

    On Sunday, January 27, 2019, 8:51:23 PM CST, Matthew Orres <notifications@github.com> wrote:  
 
 
For what it's worth, my corporate email is also managed by G Suite, and I was able to receive an email from the site without issue, so perhaps the improved formatting (I also see that I've since bumped it up to a 10/10 rating by mail-tester.com) is pleasing to G-Suite. Please report back and let me know, thanks!

**Comment by mattheworres** [comment]
Weird. I know it sounds silly, but have you checked all spam folders and everything else? My mail server shows that that email was indeed successfully delivered to the Google servers.

I approved your accounts so you can go ahead and use the app as you wish. Let me know if you can find more evidence to help figure this out, I appreciate the followup.

**Comment by itsrobbyg** [comment]
Yeah nothing in the spam folder. As I stated in an earlier email, my first inclination is the DKIM authentication:
About DKIM - G Suite Admin Help

| 
| 
|  | 
About DKIM - G Suite Admin Help

Help prevent email spoofing on outgoing messagesUse the DomainKeys Identified Mail (DKIM) standard to help preve...
 |

 |

 |




    On Tuesday, February 12, 2019, 8:31:31 PM CST, Matthew Orres <notifications@github.com> wrote:  
 
 
Weird. I know it sounds silly, but have you checked all spam folders and everything else? My mail server shows that that email was indeed successfully delivered to the Google servers.

I approved your accounts so you can go ahead and use the app as you wish. Let me know if you can find more evidence to help figure this out, I appreciate the followup.

**Comment by mattheworres** [comment]
I'll work to get DKIM authentication setup once I migrate over to the new domain, recently renamed the app so it'd be less work for me if I wait until I get that done. I appreciate the patience and help on this.

**Comment by mattheworres** [comment]
So, I signed up for a DKIM monitoring service sometime after my last comment, and I have only ever received 100% aligned reports since this occurred.

It's either that I'm missing something very obvious, or this is just a hard to track down bug. Feel free to reopen if you continue to get issues with your GSuite account and the app.
