### ISSUE TITLE
Deployment setup issue. Exit Code: 2(Misuse of shell builtins) PHPDraft 2.2.0

### ISSUE THREAD

**Issue by TheGoe4** [mattheworres/hootdraft#77]
Hi, I run PHP vendor/bin/dep setup production and go through all the steps.

It executes task PHPdraft:copy files but on the next one it fails with this error code.

✔ Ok
✔ Executing task phpdraft:copyfiles
➤ Executing task phpdraft:replacevalues

                                                                               
  [Symfony\Component\Process\Exception\ProcessFailedException]                 
  The command "sed -i '' 's|{phpdraft.dbHost}|localhost|g' appsettings.php ap  
  psettings.php" failed.                                                       
  Exit Code: 2(Misuse of shell builtins)                                       
  Working directory: /home/ducky/Downloads/PHPDraft_2.2.0_Official             
  Output:                                                                      
  ================                                                             
  Error Output:                                                                
  ================                                                             
  sed: can't read s|{phpdraft.dbHost}|localhost|g: No such file or directory   
                                                                               

setup [-p|--parallel] [--no-hooks]

----------------------------------------

PHP version

PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

Composer version 2.0.8 2020-12-03 17:20:38

Any Help would be appreciated.

**Comment by TheGoe4** [comment]
fixed this, in the _setup_tasks.php file changed line near the very bottom to.


 runLocally("sed -i 's|{phpdraft.$property}|$value|g' $file $file");

**Comment by mattheworres** [comment]
@TheGoe4 could you open a PR against master with this fix? I'll test it and verify it works for me, too.
